spring:
  application:
    name: config-client
  cloud:
    config:
      #指明远程仓库分支
      label: master
      #dev 开发环境 test测试环境 pro正式环境
      profile: dev
      #指明配置服务中心网址
      uri: http://localhost:8888/
server:
  port: 8881  #此处远程配置也配置了相同的属性，所以以远程的配置为准
