spring:
  application:
    name: config-client
  cloud:
    config:
      #指明远程仓库分支
      label: master
      #dev 开发环境 test测试环境 pro正式环境
      profile: dev
      #指明配置服务中心网址
      #uri: http://localhost:8888/  #此时在读取配置文件不再写ip地址，而是服务名，这时如果配置服务部署多份，通过负载均衡，从而高可用
      discovery:
        #是从配置中心读取文件
        enabled: true
        #配置中心的servieId，即服务名
        service-id: config-server
server:
  port: 8881  #此处远程配置也配置了相同的属性，所以以远程的配置为准；
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
